import Head from 'next/head'
// import {BsFillMoonStarsFill} from 'react-icons/bs'
import 'bootstrap/dist/css/bootstrap.min.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
// import {faGithub } from '@fortawesome/free-brands-svg-icons'



import {
  AiFillGithub,
  AiFillLinkedin,

} from "react-icons/ai";
import Image from 'next/image';
import sana from "../public/sana.jpg";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import website from '../public/website.png';
import language from '../public/language.png';
import Carize from '../public/Carize.png';

export default function Home() {
 

  return (
    <div> 
     <Head>
      <title>Sana Fatima Portofolio</title>
      <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
     <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section className='min-h-screen'>
      <nav className='py-10 mb-12 flex justify-between dark:text-white'>
      <h1 className='text-xl font-burtons'>DevelopedbySana</h1>
      <ul className='flex items-center'>
        {/* <li>
          <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
        </li> */}
        <li>
          <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-5 py-2 rounded-md ml-8' href="#">Resume</a></li>
      </ul>
      </nav>

      <div className='text-center p-10'>
        <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Sana Fatima</h2>
        <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Frontend Developer and Designer</h3>
        <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg  mx-auto dark:text-gray-200'>
          I am a Frontend Developer and Designer. Freelancer providing services of web development. 
        </p>
      </div>

      <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
      <a href='https://www.linkedin.com/in/sana-fatima-26816a260/' target='_blank' rel='noopener noreferrer' className="text-gray-500 hover:text-blue-700">
        <AiFillLinkedin/>
        </a>
        <a href="https://github.com/sanafatima8"  target='_blank' rel='noopener noreferrer' className="text-black-500 hover:text-black">
        <AiFillGithub/>
        </a>
      </div>
     
     <div className='mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96'>
     <Image src={sana} />
     </div>    
      </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200' >
            Skilled and motivated Software Frontend Web Developer passionate about creating exceptional  <span className='text-teal-500'>user experiences</span>.
             I have a strong front-end development background and I can deliver high-quality, <span className='text-teal-500'>responsive</span>, and visually appealing web applications. 
          
            </p>
           
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center items-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <Image  src={website} width={100} height={100}/>

              {/* <Image src={design} width={100} height={100} /> */}
              <h3 className='text-lg font-medium pt-8 pb-2'>Responsive Website Development</h3>
              <p className='py-2'>
                Creating Responsive designs.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>CSS Frameworks</p>
              <p className='text-gray-800 py-1'>Media Queries</p>
              <p className='text-gray-800 py-1'>CSS Flexbox</p>
            </div>
            <div className="text-center items-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <Image  src={language} width={100} height={100}/>

              {/* <Image src={design} width={100} height={100} /> */}
              <h3 className='text-lg font-medium pt-8 pb-2'>Languages and frameworks</h3>
              <p className='py-2'>
                Using updated language
              </p>
              <h4 className='py-4 text-teal-600'>Languages and frameworks I use</h4>
              <p className='text-gray-800 py-1'>HTML</p>
              <p className='text-gray-800 py-1'>Css</p>
              <p className='text-gray-800 py-1'>Tailwind Css</p>
              <p className='text-gray-800 py-1'>Bootstrap</p>
              <p className='text-gray-800 py-1'>JavaScript</p>
              <p className='text-gray-800 py-1'>ReactJs</p>

            </div>

            <div className="text-center items-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <Image  src={consulting} width={100} height={100}/>

              <h3 className='text-lg font-medium pt-8 pb-2'>Custom Web Design</h3>
              <p className='py-2'>
                Creating custom web designs.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Graphic Design Software</p>
              <p className='text-gray-800 py-1'>Typography Tools</p>
              <p className='text-gray-800 py-1'>Grid Systems</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1  '>Portofolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 ' >
            Highly skilled and motivated Software Frontend Web Developer passionate about creating exceptional user experiences.
           I have a strong front-end development background and I can deliver high-quality, <span className='text-teal-500'>responsive</span> , and visually appealing web applications.
           My expertise lies in utilizing cutting-edge technologies like HTML, CSS, Tailwind CSS JavaScript, and frameworks like ReactJS to develop intuitive and dynamic user interfaces.
            I am proficient in translating design concepts into pixel-perfect layouts, ensuring cross-browser compatibility, and optimizing web performance.
             With a keen eye for detail, I prioritize clean and <span className='text-teal-500'> maintainable code</span>, following industry best practices and adhering to coding standards.
    
             
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 ">
            I am eager to contribute my expertise to a dynamic team, where I can make a important impact and continue to grow as a front-end web developer.
            </p>
          </div>

          <div className='flex flex-col gap-10 py=10 mb-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1 mb-10 '>
              <Image src={Carize} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>

            {/* <div className='basis-1/3'>
              <Image src={} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>

            <div className='basis-1/3'>
              <Image src={} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>

            <div className='basis-1/3'>
              <Image src={} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>

            <div className='basis-1/3'>
              <Image src={} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>

            <div className='basis-1/3'>
              <Image src={} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>

            <div className='basis-1/3'>
              <Image src={} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div> */}


          </div>
        </section>
    
     </main>
    </div>
  );
}